### PR TITLE
JsonParser handler broken when the response is fragmented (Fixes #533)

### LINKED ISSUE #533: JsonParser handler looks broken when the response is fragmented
**Describe the bug**
If the response is such big that it is fragmented, the JsonParser processor breaks with:

```bash
16:38:59,609 WARN  (epollEventLoopGroup-2-1) [i.h.c.h.j.StreamQueue] Too many buffered fragments, dropping data.
16:38:59,609 WARN  (epollEventLoopGroup-2-1) [i.h.c.h.j.StreamQueue] Too many buffered fragments, dropping data.
16:38:59,609 WARN  (epollEventLoopGroup-2-1) [i.h.c.h.j.StreamQueue] Too many buffered fragments, dropping data.

16:38:59,610 WARN  (epollEventLoopGroup-2-1) [i.h.c.h.j.StreamQueue] Too many buffered fragments, dropping data.
16:38:59,612 ERROR (epollEventLoopGroup-2-1) [i.h.h.s.HttpResponseHandlersImpl] #0 Response body processing failed on io.hyperfoil.http.steps.HttpResponseHandlersImpl@476b0c84 java.lang.IndexOutOfBoundsException: index: -879788, length: 1 (expected: range(0, 65536))
	at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390)
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1379)
	at io.netty.buffer.AbstractByteBuf.getByte(AbstractByteBuf.java:355)
	at io.hyperfoil.core.handlers.json.JsonUnquotingTransformer.transform(JsonUnquotingTransformer.java:48)
	at io.hyperfoil.core.handlers.json.JsonUnquotingTransformer.process(JsonUnquotingTransformer.java:39)
	at io.hyperfoil.core.handlers.json.JsonHandler.record(JsonHandler.java:63)
	at io.hyperfoil.core.handlers.json.StreamQueue.consume(StreamQueue.java:115)
	at io.hyperfoil.core.handlers.json.JsonParser$Context.tryRecord(JsonParser.java:441)
	at io.hyperfoil.core.handlers.json.JsonParser$Context.parse(JsonParser.java:308)
	at io.hyperfoil.core.handlers.json.JsonHandler$Context.parse(JsonHandler.java:66)
	at io.hyperfoil.core.handlers.json.JsonHandler.process(JsonHandler.java:34)
	at io.hyperfoil.http.steps.HttpResponseHandlersImpl.handleBodyPart(HttpResponseHandlersImpl.java:250)
	at io.hyperfoil.http.connection.Http1xResponseHandler.onBodyPart(Http1xResponseHandler.java:514)
	at io.hyperfoil.http.connection.Http1xResponseHandler.readChunks(Http1xResponseHandler.java:278)
	at io.hyperfoil.http.connection.Http1xResponseHandler.readBody(Http1xResponseHandler.java:239)
	at io.hyperfoil.http.connection.Http1xResponseHandler.channelRead(Http1xResponseHandler.java:91)

```

**To Reproduce**
1. Ensure the SUT returns a very big response
2. Run a benchmark calling such endpoint
3. Check the Hyperfoil logs and you'd see the error

**Expected behavior**
It should work regardless of the response size

**Additional context**
Workaround: store the response body as variable and then use JsonProcessor as separate step

### PR DESCRIPTION
**Pull request by franz1981**
## Fixes Issue

Fixes #533 

## Changes proposed

It is allowing to enlarge both the StreamQueue and the pool which holds `BytesStream`.
Additionally it is simplifying and commenting some code, reusing it, to improve readability and make it less error prone.

## Check List (check all the applicable boxes) 

- [x] All new and existing tests passed.
- [x] `StreamQueue::consume` is still uncovered by tests (TODO)

### CODE REVIEW

File: core/src/main/java/io/hyperfoil/core/handlers/json/StreamQueue.java [hunk 1]
```diff
@@ -13,25 +14,40 @@
...
+      userIndex = newUserIndex;
+      parts = newParts;
+      assert parts[tail] == null;
+   }
+
    public int append(ByteStream stream) {
       if (parts[tail] != null) {
-         log.warn("Too many buffered fragments, dropping data.");
-         parts[tail].release();
+         enlargeCapacity();
```
Comment (franz1981) [inline core/src/main/java/io/hyperfoil/core/handlers/json/StreamQueue.java:50]: I Will probably retain the warn here so we can spot that a top big number of fragments are received

**Comment by franz1981** [comment]
@lampajr I'm adding some fine grain tests since `StreamQueue::release` looks broken - see `appendAndRemoveWithEnlargementShouldContainsTheRightData` test

File: core/src/main/java/io/hyperfoil/core/handlers/json/JsonParser.java [hunk 2]
```diff
@@ -376,8 +376,24 @@ public void parse(ByteStream data, Session session, boolean isLast) {
                stream.consume(lastOutputIndex, safeOutputIndex, record, this, session, isLast);
                lastOutputIndex = safeOutputIndex;
             }
-            stream.release(readerIndex);
+            stream.releaseUntil(readerIndex);
+         }
+      }
+
+      private int safeReleaseIndex() {
```
Comment (franz1981) [inline core/src/main/java/io/hyperfoil/core/handlers/json/JsonParser.java:383]: While fixing this, I've tried to improve `StreamQueue::releaseUntil` to be able to remove the part if the `index` is exactly the last addressable one in the part, but it has broke few tests :"( so I'm not sure yet if change that behaviour and picked a more conservative direction :/ - beaten by the code complexity

File: core/src/main/java/io/hyperfoil/core/handlers/json/StreamQueue.java [hunk 3]
```diff
@@ -5,118 +5,261 @@
...
 
-   private final ByteStream[] parts;
+   private ByteStream[] parts;
    // indices used by users for the beginning (readerIndex) of the bytestream
-   private final int[] userIndex;
-   private final int mask;
+   private int[] userIndex;
+   private int mask;
    private int end = -1;
    private int tail = 0;
```
Comment (franz1981) [inline core/src/main/java/io/hyperfoil/core/handlers/json/StreamQueue.java:22]: I think that `tail` could be removed and just check the next(end) == `null` instead - I'll try to make this change on monday

File: core/src/main/java/io/hyperfoil/core/handlers/json/StreamQueue.java [hunk 4]
```diff
@@ -5,118 +5,261 @@
...
 import org.apache.logging.log4j.Logger;
+import org.jctools.util.Pow2;
 
 /**
  * This serves as an abstraction over several {@link ByteStream bytestreams} so that users can just append
  * new buffers to the back and use absolute positioning with single index.
  */
 public class StreamQueue {
-   protected static final Logger log = LogManager.getLogger(StreamQueue.class);
+   private static final Logger log = LogManager.getLogger(StreamQueue.class);
```
Comment (franz1981) [inline core/src/main/java/io/hyperfoil/core/handlers/json/StreamQueue.java:15]: I've retained this one because if we keep on allocating past a certain threshold we can decide to warn the user of an allocation

File: http/src/test/java/io/hyperfoil/http/ChunkedTransferTest.java [hunk 5]
```diff
@@ -58,6 +69,52 @@ protected void initRouter() {
          }
          response.end();
       });
+      router.route("/test4").handler(ctx -> {
+         if (fooValue == null) {
+            final byte[] hugeValue = new byte[FOO_VALUE_SIZE];
+            Arrays.fill(hugeValue, (byte) 'a');
+            final String hugeValueString = new String(hugeValue, 0, 0, hugeValue.length);
```
[the remark this answers is not in the document]
Comment (franz1981) [reply http/src/test/java/io/hyperfoil/http/ChunkedTransferTest.java:76]: I think you didn't looked at the Java doc of that method. It is not the array length, but the start offset

File: core/src/main/java/io/hyperfoil/core/handlers/json/StreamQueue.java (hunk 3 above)
Comment (lampajr) [reply core/src/main/java/io/hyperfoil/core/handlers/json/StreamQueue.java]: makes sense as the `tail` is always `end + 1`

Comment (franz1981) [reply core/src/main/java/io/hyperfoil/core/handlers/json/StreamQueue.java]: Yep, in the queues impl I made for JCtools we don't save both end and tail since the latter can be easily computed. In the lady commit version I made, it is like that already

**Comment by franz1981** [comment]
Ready for review @lampajr :pray:

**Review by lampajr — APPROVED** [review]
Thanks a lot @franz1981

I also tested it locally with a big JSON (that was failing before) and it looks great!

**Comment by franz1981** [comment]
@lampajr just for the record, feel free to share any profiling data from hyperfoil too so we can attach it here and one day, unless surprises, handle it

**Comment by lampajr** [comment]
> @lampajr just for the record, feel free to share any profiling data from hyperfoil too so we can attach it here and one day, unless surprises, handle it

yeah sure, I am planning to share something in these days 🚀
