### PR TITLE
fix #45 only write all.json if there is data

### LINKED ISSUE #45: JSON stats persister errors
I've seen some errors from the JSON stats persister when the deployment fails:
```
07:46:08,818 ERROR (vert.x-worker-thread-9) [i.h.c.ControllerVerticle] Failed to persist statistics com.fasterxml.jackson.core.JsonGenerationException: Current context not Object but root
        at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1961)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeEndObject(UTF8JsonGenerator.java:351)
        at io.hyperfoil.core.impl.statistics.StatisticsStore.walkPhaseIterFork(StatisticsStore.java:272)
        at io.hyperfoil.core.impl.statistics.StatisticsStore.writeJson(StatisticsStore.java:307)
        at io.hyperfoil.core.impl.statistics.StatisticsStore.persist(StatisticsStore.java:480)
        at io.hyperfoil.clustering.ControllerVerticle.lambda$persistRun$31(ControllerVerticle.java:503)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by willr3**

### CODE REVIEW

File: core/src/main/java/io/hyperfoil/core/impl/statistics/StatisticsStore.java [hunk 1]
```diff
@@ -471,15 +474,15 @@ public void persist(Path dir) throws IOException {
       Data[] sorted = this.data.values().stream().flatMap(map -> map.values().stream()).toArray(Data[]::new);
       Arrays.sort(sorted, Comparator.comparing((Data d) -> d.phase).thenComparing(d -> d.metric).thenComparingInt(d -> d.stepId));
 
-      try (FileOutputStream stream = new FileOutputStream(dir + File.separator + "all.json")) {
-         JsonFactory jfactory = new JsonFactory();
-         jfactory.setCodec(new ObjectMapper());
-         JsonGenerator jGenerator = jfactory.createGenerator(stream, JsonEncoding.UTF8);
-         jGenerator.setCodec(new ObjectMapper());
+         try (FileOutputStream stream = new FileOutputStream(dir + File.separator + "all.json")) {
```
Comment (rvansa) [inline core/src/main/java/io/hyperfoil/core/impl/statistics/StatisticsStore.java]: This indent looks wrong

Comment (willr3) [reply core/src/main/java/io/hyperfoil/core/impl/statistics/StatisticsStore.java]: fixed that too, odd that it passed checkstyles

File: core/src/main/java/io/hyperfoil/core/impl/statistics/StatisticsStore.java [hunk 2]
```diff
@@ -402,60 +403,62 @@ public void accept(String key, Data data) {
...
+                                 jGenerator.writeNumberField("minSessions", record.low);
+                                 jGenerator.writeNumberField("maxSessions", record.high);
+                                 jGenerator.writeEndObject();
+                              }
+                              jGenerator.writeEndArray();
                            }
-                           jGenerator.writeEndArray();
                         }
+                     } catch (IOException e) {
+                        e.printStackTrace();
```
Comment (rvansa) [inline core/src/main/java/io/hyperfoil/core/impl/statistics/StatisticsStore.java]: I missed this first time...
